const errorCodes = {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INVALID_FIELDS: "INVALID_FIELDS",
    ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
    VALIDATION_ERROR:"VALIDATION_ERROR",
    ACCESS_DENIED: "ACCESS_DENIED",
    UNAUTHORISED: "UNAUTHORISED"
  };
  
  module.exports = errorCodes;
  